name: release

on:
  push:
#    branches:
#      - 'release-v*'
    tags:
      - 'release-v*'

jobs:
  release:
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@master
    - uses: azure/container-actions/docker-login@master
      with:
        login-server: registry.cn-hongkong.aliyuncs.com
        username: ${{ secrets.ALIYUN_SHENZHEN_REGISTER_USERNAME }}
        password: ${{ secrets.ALIYUN_SHENZHEN_REGISTER_PASSWORD }}

    - name: Push the image to aliyun register
      run: |
        docker build --rm -t registry.cn-hongkong.aliyuncs.com/strengthening/pyanalysis:${GITHUB_REF:18} .
        docker push registry.cn-hongkong.aliyuncs.com/strengthening/pyanalysis:${GITHUB_REF:18}